language: python
python: "2.7"
branches:
  only:
    - master
    - /^dev-.*$/
# command to install dependencies
install: "pip install -r requirements.txt"
# build database
env:
  - DATABASE_URL:
addons:
  postgresql: "9.3"
before_script:
  - psql -c "create datase system_test" -U postgres
# command to run tests
script: nosetests
# deployment
deploy:
  provider:
    heroku
  api_key: 98fb273a-fbdd-4a91-969a-e5205032e31c
  app: poll-system
